### ISSUE TITLE
Revise token list fetch function to fetch lists from github

### ISSUE THREAD

**Issue by keithfrazier98** [dataxfi/datax.js#10]
The current implementation of the [fetchPreparedTokenList](https://github.com/dataxfi/datax.js/blob/9082cdca9d4908e696edf8fb009a23b6c39048b8/src/TokenList.ts#L318) function fetches the token lists from google drive. The new implementation of the token lists script as a GitHub action will render this function useless. The function needs to be revised to fetch from the [scripts](https://github.com/dataxfi/scripts) repository on Github. 

This implementation also posed another issue for datax.js in general. As a developer using datax.js to build their dapp, they would need to have a google service account and implement the token list operations exactly how Datapolis did, as well as a standalone server dedicated to hosting the script. Their application would also need multiple env variables for authentication and what have you. With the [scripts](https://github.com/dataxfi/scripts) repository now being open source, it was also very tailored to the Datapolis legacy use case and didn't pose much value to a developer who wasn't interested in maintaining a server to have the token list preparation on a cron schedule. 

Having the token lists available in the [scripts](https://github.com/dataxfi/scripts) on top of having the GitHub action to update the token list on a schedule poses more value to developers using datax.js, and alleviates the need to maintain another server and google cloud account dedicated to this purpose.

**Comment by akankshapatel30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [datax.js repo issues](https://trello.com/c/XrpCjb4x/3-dataxjs-repo-issues)

**Comment by 0xrishabh** [comment]
The function is updated https://github.com/dataxfi/datax.js/blob/main/src/TokenList.ts#L325
so I think we can close this one.
