### ISSUE TITLE
Add error codes to datax.js

### ISSUE THREAD

**Issue by keithfrazier98** [dataxfi/datax.js#11]
All errors are currently being thrown and logged, and none of them have serialized information or standard convention. This makes having detailed error messages in an app hard to handle because you have to recognize phrases in the error message text. 

There should be a documented and standardized system for error codes so that Datapolis and other developers can utilize these codes to handle errors gracefully. 

In the circumstance of a transaction being mined into an uncle block or not being mined within 50 blocks, a developer would be able to catch this and either continue watching a transaction or report a successful transaction respective to the error.

**Comment by akankshapatel30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [datax.js repo issues](https://trello.com/c/XrpCjb4x/3-dataxjs-repo-issues)
