### ISSUE TITLE
Add types file to datax.js to be single source of types in datax.js and datax.js projects. 

### ISSUE THREAD

**Issue by keithfrazier98** [dataxfi/datax.js#13]
The types used in datax.js are defined in the files in which they are used. These types throughout the project should be brought into one types file for easier reference. Further, types imported from uniswap should be defined in datax.js to fit datax.js's specific use cases. This would alleviate a dep and add clarity to the types needed in datax.js and dApps built with datax.js, as well as streamlining type inheritance for dApps.

**Comment by akankshapatel30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [datax.js repo issues](https://trello.com/c/XrpCjb4x/3-dataxjs-repo-issues)
