### ISSUE TITLE
Convert max exchange functions in Datapolis to be in Datax.js

### ISSUE THREAD

**Issue by keithfrazier98** [dataxfi/datax.js#9]
Currently, the max exchange algorithms used to determine the max exchange, stake, and unstake, are all written directly in Datapolis. These functions should be transferred and featured directly in datax.js.

**Comment by akankshapatel30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [datax.js repo issues](https://trello.com/c/XrpCjb4x/3-dataxjs-repo-issues)
